version: '2'

services:
    webserver:
        image: helrick/forcast
        expose:
            - ${APACHE2_PORT}
        ports:
            - ${SERVER_ADDRESS}:${APACHE2_PORT}:${APACHE2_PORT}
        volumes:
            - ./mongodb:/data/db
        command: >
            bash -c "sudo mongod --fork --logpath /var/log/mongodb.log
            && python3 /var/www/html/setup_script/setup.py -r /var/www/html -g ${ORGANISM} -v ${ASSEMBLY} -fa2bit /var/www/html/tools/usrLocalBin/faToTwoBit -b /var/www/html/dependencies/ncbi-blast-2.7.1+/bin
            && sudo service apache2 start
            && tail -f /dev/null"
